---
# tasks file for netbox
- name: Build Netbox
  include_tasks: build.yml
  tags:
    - never
    - netbox_build

- name: Add a repository
  kubernetes.core.helm_repository:
    name: "{{ netbox_name }}"
    repo_url: "{{ netbox_repo_url }}"

- name: Remove Netbox
  kubernetes.core.helm:
    name: "{{ netbox_name }}"
    release_namespace: "{{ netbox_release_namespace }}"
    state: absent
    wait: true
  tags:
    - never
    - netbox_cleanup

- name: Remove PersistenVolume
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: "{{ item.key }}"
          #        namespace: "{{ netbox_release_namespace }}"
  loop: "{{ volumes | dict2items }}"
  vars:
    volumes:
      data-netbox-postgresql-0: 8Gi
      netbox-media: 1Gi
      redis-data-netbox-redis-master-0: 8Gi
      redis-data-netbox-redis-replicas-0: 8Gi
      redis-data-netbox-redis-replicas-1: 8Gi
      redis-data-netbox-redis-replicas-2: 8Gi
  tags:
    - never
    - netbox_cleanup

- name: Remove namespace for Netbox
  kubernetes.core.k8s:
    name: "{{ netbox_release_namespace }}"
    api_version: v1
    kind: Namespace
    state: absent
    wait: true
  tags:
    - never
    - netbox_cleanup

- name: Create namespace for Netbox
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ netbox_release_namespace }}"
        labels:
          pod-security.kubernetes.io/enforce: privileged

- name: Deploy Netbox
  kubernetes.core.helm:
    name: "{{ netbox_name }}"
    chart_ref: "{{ netbox_chart_ref }}"
    chart_version: "{{ netbox_chart_version }}"
    release_namespace: "{{ netbox_release_namespace }}"
    create_namespace: false
    values:
      image:
        registry: essigke
        repository: netbox
        tag: latest-plugins
        pullPolicy: Always
      secretKey: "{{ netbox_secret_key }}"
      superuser:
        name: "{{ netbox_superuser_username }}"
        password: "{{ netbox_superuser_password }}"
        email: "{{ netbox_superuser_email }}"
        apiToken: "{{ netbox_superuser_api_token }}"
      global:
        storageClass: "{{ netbox_storage_class }}"
      redis:
        enabled: true
        global:
          redis:
            password: "{{ netbox_redis_password }}"
      postgresql:
        enabled: true
          #        rbac:
          #          create: true
        auth:
          #          database: mynetbox
          #          username: mynetbox
          password: "{{ netbox_postgresql_password }}"
        global:
          postgresql:
            auth:
              #              database: mynetbox
              #              username: mynetbox
              password: "{{ netbox_postgresql_password }}"
                #        passwordUpdateJob:
                #          enabled: true
      service:
        type: LoadBalancer
        loadBalancerIP: "{{ netbox_loadbalancer_ip }}"
        loadBalancerClass:  "{{ netbox_loadbalancer_class }}"
      plugins:
         - "netbox_routing"
         - "netbox_dns"
         - "netbox_kea"
         - "netbox_secrets"
         - "netbox_topology_view"
          #       pluginsConfig:
          #- name: Create pod to create directories
          #  kubernetes.core.k8s:
          #    state: present
          #    namespace: "{{ netbox_release_namespace }}"
          #    definition:
          #      apiVersion: v1
          #      kind: Pod
          #      metadata:
          #        name: gen-vol-path
          #        namespace: "{{ netbox_release_namespace }}"
          #      spec:
          #        containers:
          #          - name: gen-vol-path
          #            image: busybox:latest
          #            imagePullPolicy: IfNotPresent

          #- name: Create a PersistenVolume
          #  include_tasks: create_pv.yml
          #  loop: "{{ volumes | dict2items }}"
          #  vars:
          #    volumes:
          #      data-netbox-postgresql-0: 8Gi
          #      netbox-media: 1Gi
          #      redis-data-netbox-redis-master-0: 8Gi
          #      redis-data-netbox-redis-replicas-0: 8Gi
          #      redis-data-netbox-redis-replicas-1: 8Gi
          #      redis-data-netbox-redis-replicas-2: 8Gi


        #- name: Remove Pod
        #  kubernetes.core.k8s:
        #    state: absent
        #    api_version: v1
        #    kind: Pod
        #    namespace: "{{ netbox_release_namespace }}"
        #    name: gen-vol-path


- name: Netbox takes ages to get ready (15min?)
  #  ansible.builtin.pause:
  #    minutes: 12
  ansible.builtin.wait_for:
    sleep: 60
    host: "{{ netbox_loadbalancer_ip }}"
    port: 80

- name: "Include all .yaml and .yml files from {{ netbox_data_dir }}"
  ansible.builtin.include_vars:
    dir: "{{ netbox_data_dir }}"
    ignore_unknown_extensions: true
    extensions:
      - 'yaml'
      - 'yml'
    ignore_files: 
      - secrets.sops.yml
  tags:
   - netbox_setup

- name: "Include secrets from {{ netbox_data_dir }}"
  community.sops.load_vars:
    file: "{{ netbox_data_dir }}/secrets.sops.yml"
  tags:
   - netbox_setup

# For the moment I only need {{ netbox_data_dir }}/global_vars.yml
- name: Create permission with all parameters
  netbox.netbox.netbox_permission:
    netbox_url: "http://{{ netbox_loadbalancer_ip }}"
    netbox_token: "{{ netbox_superuser_api_token }}"
    validate_certs: false
    data:
      name: Ansible permission
      description: Ansible Configuration Management System
      enabled: true
      actions:
        - view
        - add
        - change
        - delete
        - extreme_administration
      object_types: |
        {% set output = [] %}
        {% for ndm in netbox_data_models %}
        {% if ndm.type is string %}
        {% set _ = output.append(ndm.type) %}
        {% else %}
        {% for ndml in ndm.type %}
        {% set _ = output.append(ndml) %}
        {% endfor %}
        {% endif %}
        {% endfor %}
        {{ output }}
    state: present
  tags:
    - netbox_setup

# Currently missing, may be added later:
      #        #        - dcim.frontport
      #        #        - dcim.rearport
      #          #        - wireless.wirelesslink
      #          #        - wireless.wirelesslangroup
      #          #        - dcim.region
      #          #        - dcim.sitegroup
      #          #        - dcim.rack
      #          #        - extras.customlink

- name: Create user for Ansible
  netbox.netbox.netbox_user:
    netbox_url: "http://{{ netbox_loadbalancer_ip }}"
    netbox_token: "{{ netbox_superuser_api_token }}"
    validate_certs: false
    data:
      is_active: true
      is_staff: false
      first_name: Ansible
      last_name: Configuration Management System
      permissions: Ansible permission
      username: "{{ netbox_ansible_user }}"
      password: "{{ netbox_ansible_password }}"
    state: present
  tags: 
    - netbox_setup

- name: Create token within NetBox with only required information
  netbox.netbox.netbox_token:
    netbox_url: "http://{{ netbox_loadbalancer_ip }}"
    netbox_token: "{{ netbox_superuser_api_token }}"
    validate_certs: false
    data:
      user: "{{ netbox_ansible_user }}"
      key: "{{ netbox_ansible_token }}"
    state: present
  tags: 
    - netbox_setup
          
- name: Setup data in Netbox
  include_tasks: setup_netbox.yml
  tags: 
    - netbox_setup

- name: Build inventory.yml from Netbox
  include_tasks: 
    file: inventory_builder.yml
    apply:
      tags:
        - netbox_setup
  tags:
    - netbox_setup

- name: Create read-only token within NetBox
  netbox.netbox.netbox_token:
    netbox_url: "http://{{ netbox_loadbalancer_ip }}"
    netbox_token: "{{ netbox_superuser_api_token }}"
    validate_certs: false
    data:
      user: "{{ netbox_ansible_user }}"
      key: "{{ netbox_ansible_ro_token }}"
      write_enabled: false
    state: present
  tags:
    - netbox_setup

- name: Write group_vars/all.yml
  copy:
    dest: "{{ inventory_dir }}/group_vars/all.yml"
    content: |
      # Managed by Ansible role NetBox
      ansible_nb_url: "http://{{ netbox_loadbalancer_ip }}"
      ansible_nb_token: "{{ netbox_ansible_ro_token }}"
  tags:
    - netbox_setup
